Add a team.qmd page
r-multiverse/r-multiverse.github.io pull request #15
Opened 2024-04-09 13:26 UTC by wlandau

There are sections for team members and the roles of each member.

2024-05-30 10:58 UTC, shikokuchuo requested changes
Can we update with Jeroen and Maelle please.

Also this would be a natural place for a note of appreciation on R Consortium support. We probably want to do this more broadly but can start here.

2024-06-06 18:07 UTC, wlandau commented
> Can we update with Jeroen and Maelle please.

Last I heard, they expressed a preference not to be listed. (Please correct me if I am wrong, @maelle and @jeroen). I think it would be best to merge this version and invite PRs from people going forward.

> Also this would be a natural place for a note of appreciation on R Consortium support. We probably want to do this more broadly but can start here.

I agree, done in 7e2c87766c2c561b94eae2a4eaa7bba111f8c0fd

2024-06-06 18:27 UTC, shikokuchuo commented
I'm ok with that approach.

2024-06-06 18:27 UTC, shikokuchuo approved these changes

2024-06-06 18:33 UTC, merged